const fs=require('fs'),vm=require('vm'),assert=require('assert');
const T=require('../vendor/three.min.js');
const sandbox={THREE:T,window:{},document:{createElement(){return{width:128,height:128,getContext(){return{fillRect(){},fillText(){}}}}}}};
let source=fs.readFileSync('brick-renderer.js','utf8').replace('  window.BrickRenderer=BrickRenderer;','  window.BrickRenderer=BrickRenderer;window.test={brick,cabin,chicken,geometryCache,STUD_PITCH};');
vm.runInNewContext(source,sandbox);
const {brick,cabin,chicken,geometryCache,STUD_PITCH}=sandbox.window.test;
assert.equal(STUD_PITCH,.25);
const parts=[];chicken(parts);
const bodyStud=geometryCache.get('stud:0.075');assert(bodyStud);
const grass=[];brick(grass,0,0,0,4,4,1,'#4f9d38');
assert.equal(grass.filter(p=>p.g===bodyStud).length,16);
const centers=grass.filter(p=>p.g===bodyStud).map(p=>p.matrix.elements[12]);
const xs=[...new Set(centers)].sort((a,b)=>a-b);
for(let i=1;i<xs.length;i++)assert(Math.abs(xs[i]-xs[i-1]-.25)<1e-8);
const renderer=Object.create(sandbox.window.BrickRenderer.prototype);renderer.scene=new T.Scene();
renderer.createRow({y:0,type:'grass',trees:[],flowers:[],items:[]});
assert(!geometryCache.has('stud:0.15'),'Grass must not use oversized studs');
const raft=renderer.createRow({y:1,type:'water',trees:[],flowers:[],items:[{x:0,length:3.5}]}).moving[0].node;
assert(Math.abs(new T.Box3().setFromObject(raft).getSize(new T.Vector3()).x-3.488)<1e-5);
const cabinParts=[];cabin(cabinParts,0,0,0,'#ffbb00');
const positions=geometryCache.get('cabin-glass').attributes.position;
const bottom=[],top=[];
for(let i=0;i<positions.count;i++)(positions.getY(i)<.01?bottom:top).push([positions.getX(i),positions.getZ(i)]);
const bounds=points=>[Math.min(...points.map(p=>p[0])),Math.max(...points.map(p=>p[0])),Math.min(...points.map(p=>p[1])),Math.max(...points.map(p=>p[1]))];
const b=bounds(bottom),t=bounds(top);
assert(t[0]>b[0]&&t[1]<b[1],'Both windshields slope toward the roof along travel direction');
assert.equal(t[2],b[2]);assert.equal(t[3],b[3]);
console.log('PASS shared chicken/grass stud geometry and pitch');
console.log('PASS actual grass mesh uses standard studs');
console.log('PASS raft width and seams align to brick grid');
console.log('PASS windshields slope along the vehicle length, not width');
